name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js 24 🟢
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install dependencies 📦
        run: nci

      - name: Build Project 🏗️
        run: nr build

      - name: Lint 🔍
        run: nr lint

      - name: Typecheck
        run: nr typecheck

      - name: Audit (high severity only) 🔒
        run: pnpm audit --audit-level high
